__base__: ../DualCervixDetection/DualCervixDetection_grayscale.yaml

__import__:
    import_gen_segmentation_from_bbox_transform: &import_gen_segmentation_from_bbox_transform
        type: GenSegmentationFromBBox
        num_classes: 1

data:
    init_args:
        pipeline:
            acid:
                insert_item:
                    - [ 5, *import_gen_segmentation_from_bbox_transform ]
            iodine:
                insert_item:
                    - [ 5, *import_gen_segmentation_from_bbox_transform ]
